name: senisafe
description: "A Flutter app for elderly care with fall detection, medication reminders, and emergency support."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter UI
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.5.0

  # Firebase
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.8.4
  firebase_messaging: ^14.7.0

  # Notifications & Alerts
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  vibration: ^1.8.4

  # Sensors & Emergency Detection
  sensors_plus: ^3.0.3  # Updated for Flutter 3.7.x
  geolocator: ^14.0.0
  permission_handler: ^11.3.0
  url_launcher: ^6.2.4
  http: ^1.2.1

  # Real-time Communication
  agora_rtc_engine: ^6.3.0

  # Data Visualization & Storage
  syncfusion_flutter_charts: ^23.2.7
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.ttf
        - asset: assets/fonts/OpenDyslexic-Bold.ttf
          weight: 700
